name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install xcb
        run: sudo apt install libxcb-screensaver0 libxcb-screensaver0-dev libxcb1 libxcb1-dev libxss1 libxss-dev
      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
